version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: rails_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    volumes:
      - ./container/db/data:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: rails_dev
      DB_USERNAME: dev
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379
    entrypoint:
      - dockerize
      - -wait
      - tcp://db:5432
      - -timeout
      - 60s
      - -wait-retry-interval
      - 3s
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - db
      - redis
