version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: rails_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    volumes:
      - ./container/db/data:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
  rails:
    build:
      context: .
      dockerfile: container/rails/Dockerfile
    image: rails-k8s-practice-rails
    environment:
      DB_HOST: db
      DB_NAME: rails_dev
      DB_USERNAME: dev
      DB_PASSWORD: password
    volumes:
      - .:/app:cached
      - public-data:/app/public
      - tmp-data:/app/tmp
    entrypoint:
      - dockerize
      - -wait
      - tcp://db:5432
      - -timeout
      - 60s
      - -wait-retry-interval
      - 3s
    command: bundle exec rails s
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: container/nginx/Dockerfile
    image: rails-k8s-practice-nginx
    environment:
      SERVER_NAME: localhost
      APP_NAME: rails
      ROOT_PATH: /app/public
      SOCKET_PATH: /app/tmp/sockets/puma.sock
    volumes:
      - ./container/nginx/templates:/etc/nginx/templates
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - "8000:80"
    depends_on:
      - rails
volumes:
  public-data:
  tmp-data:
