apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rails-k8s-practice
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
          - name: POSTGRES_DB
            value: rails_dev
          - name: POSTGRES_USER
            value: dev
          - name: POSTGRES_PASSWORD
            value: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: db-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-volume
          persistentVolumeClaim:
              claimName: db-pvc
